import { existsSync } from "node:fs";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

export interface InstallBinResult {
	shimPath: string;
	binDir: string;
	onPath: boolean;
	unchanged: boolean;
	message: string;
}

function packageRoot(): string {
	return fileURLToPath(new URL("../../../", import.meta.url));
}

export function quoteShell(value: string): string {
	return `'${value.replace(/'/g, `'"'"'`)}'`;
}

/**
 * Quote a string for safe inclusion in a Windows `.cmd` batch file. cmd
 * expands `%VAR%` references *before* tokenization, so wrapping in `"…"`
 * does NOT protect against variable expansion — `%` must be doubled. The
 * other listed characters are either illegal in NTFS file names (`"`) or
 * would break batch syntax (`\r`, `\n`, `\0`); we refuse them defensively
 * rather than emit a broken shim.
 */
export function quoteForCmd(value: string): string {
	if (/[\r\n\0"]/.test(value)) {
		throw new Error(
			`Cannot install pi-proc shim: path contains an illegal character: ${JSON.stringify(value)}`,
		);
	}
	return `"${value.replace(/%/g, "%%")}"`;
}

function pathEntries(): string[] {
	return (process.env.PATH ?? "")
		.split(path.delimiter)
		.filter(Boolean)
		.map((entry) => path.resolve(entry));
}

export function isOnPath(binDir: string, entries: string[]): boolean {
	if (process.platform === "win32") {
		const target = binDir.toLowerCase();
		return entries.some((entry) => entry.toLowerCase() === target);
	}
	return entries.includes(binDir);
}

export function pathAddHint(binDir: string): string {
	if (process.platform === "win32") {
		// PowerShell is the modern default on Win10/11. Offer both the
		// current-session form and a persistent `setx` alternative.
		const psQuoted = binDir.replace(/'/g, "''");
		return (
			`Add ${binDir} to PATH. PowerShell (current session): ` +
			`$env:Path += ';${psQuoted}'  —  persistent: ` +
			`setx PATH "%PATH%;${binDir}"`
		);
	}
	return `Add ${binDir} to PATH, for example: export PATH="${binDir}:$PATH"`;
}

export function posixShim(cliPath: string): string {
	// Use `env node` so the shim survives `pi` upgrades that move/relink the
	// embedded Node binary. Falls through to whatever `node` resolves to on
	// PATH at invocation time.
	return `#!/usr/bin/env node\n// Auto-generated by pi-toolbelt proc-install-bin. Do not edit.\nimport(${JSON.stringify(`file://${cliPath}`)}).catch((error) => {\n  console.error("pi-proc shim failed:", error);\n  process.exit(1);\n});\n`;
}

export function windowsShim(cliPath: string): string {
	// Resolve `node` via PATH at call time, not the baked execPath, so the
	// shim survives pi upgrades. Pass through all args verbatim.
	return `@echo off\r\nnode ${quoteForCmd(cliPath)} %*\r\n`;
}

async function readExistingShim(filePath: string): Promise<string | null> {
	if (!existsSync(filePath)) return null;
	try {
		return await readFile(filePath, "utf8");
	} catch {
		return null;
	}
}

export async function installProcBin(
	targetDir = path.join(homedir(), ".pi", "bin"),
): Promise<InstallBinResult> {
	const binDir = path.resolve(targetDir);
	await mkdir(binDir, { recursive: true });
	const cliPath = path.join(packageRoot(), "bin", "pi-proc.mjs");
	const onPath = isOnPath(binDir, pathEntries());

	const shimPath =
		process.platform === "win32"
			? path.join(binDir, "pi-proc.cmd")
			: path.join(binDir, "pi-proc");
	const content =
		process.platform === "win32" ? windowsShim(cliPath) : posixShim(cliPath);

	const existing = await readExistingShim(shimPath);
	const unchanged = existing === content;
	if (!unchanged) {
		await writeFile(shimPath, content, "utf8");
		if (process.platform !== "win32") await chmod(shimPath, 0o755);
	}

	const baseMessage = unchanged
		? `pi-proc shim already current at ${shimPath}`
		: `Installed pi-proc shim to ${shimPath}`;
	const message = onPath
		? baseMessage
		: `${baseMessage}. ${pathAddHint(binDir)}`;

	return { shimPath, binDir, onPath, unchanged, message };
}
