/**
 * Embedded shell-completion scripts. Both scripts shell out to
 *   pi-proc __complete <context>
 * for any dynamic candidate set, so they stay in sync with the live CLI.
 */

export const BASH_COMPLETION = `# pi-proc bash completion. Generated by 'pi-proc install-completion bash'.
_pi_proc_completion() {
  local cur prev words cword
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  # Subcommand position.
  if [ "$COMP_CWORD" = "1" ]; then
    local subs
    subs=$(pi-proc __complete subcommands 2>/dev/null)
    COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    return 0
  fi

  local sub="\${COMP_WORDS[1]}"
  case "$sub" in
    attach|tail|logs|restart)
      local names
      names=$(pi-proc __complete run-names 2>/dev/null)
      COMPREPLY=( $(compgen -W "$names" -- "$cur") )
      return 0
      ;;
    stop)
      local names
      names=$(pi-proc __complete active-run-names 2>/dev/null)
      COMPREPLY=( $(compgen -W "$names --all" -- "$cur") )
      return 0
      ;;
  esac
}
complete -F _pi_proc_completion pi-proc
`;

export const ZSH_COMPLETION = `#compdef pi-proc
# pi-proc zsh completion. Generated by 'pi-proc install-completion zsh'.

_pi_proc() {
  local -a subs names
  local state line

  _arguments -C \\
    '1: :->subcommand' \\
    '*:: :->args'

  case "$state" in
    subcommand)
      subs=( \${(f)"$(pi-proc __complete subcommands 2>/dev/null)"} )
      _describe -t commands 'pi-proc subcommand' subs
      ;;
    args)
      case "$line[1]" in
        attach|tail|logs|restart)
          names=( \${(f)"$(pi-proc __complete run-names 2>/dev/null)"} )
          _describe -t runs 'run name or id' names
          ;;
        stop)
          names=( \${(f)"$(pi-proc __complete active-run-names 2>/dev/null)"} )
          _describe -t runs 'active run name or id' names
          _arguments '--all[stop all runs in this cwd]'
          ;;
      esac
      ;;
  esac
}

_pi_proc "$@"
`;
